M48
; DRILL file KiCad 10.0.1 date 2026-05-10T20:31:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-10T20:31:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C9.000
%
G90
G05
T1
X109.15Y-74.8
X109.15Y-125.8
X140.85Y-74.8
X140.85Y-125.8
T2
X116.0Y-105.5
X134.0Y-94.5
X134.0Y-105.5
T3
X116.0Y-94.5
T4
X101.43Y-76.43
X101.43Y-123.57
X148.57Y-76.43
X148.57Y-123.57
T5
X125.0Y-100.0
M30
